services:  
  web:
    build:
      context: .
      dockerfile: src/PetFamily.WEB/Dockerfile
    depends_on:
      - postgres
      - minio
      - seq
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: PetFamilyDb
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      
  seq:
    container_name: seqP2P
    image: datalust/seq:latest
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
    ports:
      - "5341:5341"
      - "8081:80"
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always
    
  mongodb:
    container_name: 'pet_mongodb'
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    volumes:
      - mongo_data:/data/db
    
volumes:
  postgres-data:
  minio_data:
  mongo_data:
